//
// Created by monty on 14/01/17.
//

#ifndef DUNGEONSOFNOUDAR_NDK_ETEXTURES_H
#define DUNGEONSOFNOUDAR_NDK_ETEXTURES_H
namespace odb {
    enum ETextures : uint8_t {
        Grass,
        Lava,
        Floor,
        Bricks,
        Arch,
        Bars,
        Begin,
        Exit,
        BricksBlood,
        BricksCandles,
        CrusaderAttack0,
        CrusaderAttack1,
        CrusaderStanding0,
        CrusaderStanding1,
        StrongDemonAttack0,
        StrongDemonAttack1,
        StrongDemonStanding0,
        StrongDemonStanding1,
        WeakDemonAttack0,
        WeakDemonAttack1,
        WeakDemonStanding0,
        WeakDemonStanding1,
        WarthogAttack0,
        WarthogAttack1,
        WarthogStanding0,
        WarthogStanding1,
        EvilSpiritAttack0,
        EvilSpiritAttack1,
        EvilSpiritStanding0,
        EvilSpiritStanding1,
        FallenAttack0,
        FallenAttack1,
        FallenStanding0,
        FallenStanding1,
        MonkAttack0,
        MonkAttack1,
        MonkStanding0,
        MonkStanding1,
        CocoonStanding0,
        CocoonStanding1,
        Shadow,
        Ceiling,
        CeilingDoor,
        CeilingBegin,
        CeilingEnd,
        Splat0,
        Splat1,
        Splat2,
        CeilingBars,
        Skybox,
        StoneGrassFar,
        GrassStoneFar,
        StoneGrassNear,
        GrassStoneNear,
        Cross,
        Crossbow,
        Falcata,
        Shield,
        Rope,
        Slot,
        MagicSeal,
        ShutDoor,
        Cobblestone
    };
}
#endif //DUNGEONSOFNOUDAR_NDK_ETEXTURES_H
