CXXFLAGS = -g -DVGA -DEA_PLATFORM_LINUX -DDONT_LOAD_LEVEL_UPON_START -fPIC -Iinclude -c -Istb -fpermissive -O6 -Ofast  -funroll-loops -funroll-all-loops -fomit-frame-pointer -fno-exceptions -ffast-math -I../fixed_point/include -Iinclude -I../stb -I../noudar-core/noudar-core/include  -I../noudar-core/EASTL/include -I../noudar-core/EASTL/test/packages/EABase/include/Common -I../noudar-rendering -I../gles2-renderer -fpermissive -Wno-narrowing -DUSE_ITEMS_INSTANTLY

OBJS = src/CRenderer.o \
    src/CRenderer_Rasterization.o \
    src/CRenderer_Tesselation.o \
     src/RasterizerCommon.o \
     src/NativeBitmap.o \
     src/CTile3DProperties.o \
     src/CPackedFileReader.o \
     src/VisibilityStrategy.o \
     ../gles2-renderer/Logger.o \
    ../gles2-renderer/LoadPNG.o \
    ../noudar-core/noudar-core/src/Vec2i.o \
    ../noudar-core/noudar-core/src/CActor.o \
    ../noudar-core/noudar-core/src/CMonster.o \
    ../noudar-core/noudar-core/src/CMonsterGenerator.o \
    ../noudar-core/noudar-core/src/CTeam.o \
    ../noudar-core/noudar-core/src/CMap.o \
    ../noudar-core/noudar-core/src/Common.o \
    ../noudar-core/noudar-core/src/CCharacter.o \
    ../noudar-core/noudar-core/src/CCharacterArchetype.o \
    ../noudar-core/noudar-core/src/CDoorway.o \
    ../noudar-core/noudar-core/src/IFileLoaderDelegate.o \
    ../noudar-core/noudar-core/src/IMapElement.o \
    ../noudar-core/noudar-core/src/CGame.o \
    ../noudar-core/noudar-core/src/CItem.o \
    ../noudar-core/noudar-core/src/CStorageItem.o \
    ../noudar-core/noudar-core/src/CGameDelegate.o \
    ../noudar-core/noudar-core/src/commands/IGameCommand.o \
    ../noudar-core/noudar-core/src/commands/CMoveActorCommand.o \
    ../noudar-core/noudar-core/src/commands/CLoadNewLevelCommand.o \
    ../noudar-core/noudar-core/src/commands/CTurnActorCommand.o \
    ../noudar-core/noudar-core/src/commands/CQuitCommand.o \
    ../noudar-core/noudar-core/src/commands/CNullCommand.o \
    ../noudar-core/noudar-core/src/commands/CEndTurnCommand.o \
    ../noudar-core/noudar-core/src/commands/CPickItemCommand.o \
    ../noudar-core/noudar-core/src/commands/CDropItemCommand.o \
    ../noudar-core/noudar-core/src/commands/CSuggestItemCommand.o \
    ../noudar-core/noudar-core/src/commands/CUseCurrentItemCommand.o \
    ../noudar-core/noudar-core/src/commands/CCycleNextItemCommand.o \
    ../noudar-core/noudar-core/src/commands/CCyclePreviousItemCommand.o \
    events.o \
    LibRetroCoreVersion/lr_main.o \
    LibRetroCoreVersion/CLRCoreRenderer.o \

TARGET = ra_noudar.so

$(TARGET):	$(OBJS)
	$(CXX) -fPIC -shared -Wl,--version-script=LibRetroCoreVersion/link.T -Wl,--no-undefined -lm -o $(TARGET) $(OBJS) $(LIBS) $(LDFLAGS)

all:   $(TARGET)

clean:
	rm -f $(OBJS) $(TARGET)
