CXX = i686-w64-mingw32-g++
LD = i686-w64-mingw32-ld

CXXFLAGS = -g -DVGA -DEA_PLATFORM_LINUX -Iinclude -c -Istb -fpermissive -c -O6 -Ofast  -funroll-loops -funroll-all-loops \
-fomit-frame-pointer -fno-exceptions -ffast-math  -I../fixed_point/include -IDOS-version -Iinclude -I../stb \
-I../noudar-core/noudar-core/include  -I../noudar-core/EASTL/include -I../noudar-core/EASTL/test/packages/EABase/include/Common \
-I../noudar-rendering -I../gles2-renderer -fpermissive -Wno-narrowing -DUSE_ITEMS_INSTANTLY -fPIC  \
-m32 -Wl,--enable-auto-image-base -Wl,--add-stdcall-alias -Wl,--enable-auto-import -lgdi32 -luser32 -lkernel32 -mwindows \
-march=i486 -mtune=i486 -D _WIN32_IE=0x0400 -D WINVER=0x400 -Wl,--subsystem,windows

LDFLAGS = -fPIC  -m32 -static-libstdc++ -static-libgcc -Wl,--enable-auto-image-base -Wl,--add-stdcall-alias \
        -Wl,--enable-auto-import -lgdi32 -luser32 -lkernel32 -mwindows -march=i486 -mtune=i486 -D _WIN32_IE=0x0400 \
        -D WINVER=0x400 -Wl,--subsystem,windows -static-libstdc++ -static-libgcc -static -m32  -lgdi32 -luser32 -lkernel32 \
        -lcomctl32

OBJS = src/CRenderer.o \
     src/RasterizerCommon.o \
     src/NativeBitmap.o \
     src/CTile3DProperties.o \
     src/CPackedFileReader.o \
     src/VisibilityStrategy.o \
     OPL2LPT/MusicSDL.o \
     ../gles2-renderer/Logger.o \
    ../gles2-renderer/LoadPNG.o \
    ../noudar-core/noudar-core/src/Vec2i.o \
    ../noudar-core/noudar-core/src/CActor.o \
    ../noudar-core/noudar-core/src/CMonster.o \
    ../noudar-core/noudar-core/src/CMonsterGenerator.o \
    ../noudar-core/noudar-core/src/CTeam.o \
    ../noudar-core/noudar-core/src/CMap.o \
    ../noudar-core/noudar-core/src/Common.o \
    ../noudar-core/noudar-core/src/CCharacter.o \
    ../noudar-core/noudar-core/src/CCharacterArchetype.o \
    ../noudar-core/noudar-core/src/CDoorway.o \
    ../noudar-core/noudar-core/src/IFileLoaderDelegate.o \
    ../noudar-core/noudar-core/src/IMapElement.o \
    ../noudar-core/noudar-core/src/CGame.o \
    ../noudar-core/noudar-core/src/CItem.o \
    ../noudar-core/noudar-core/src/CStorageItem.o \
    ../noudar-core/noudar-core/src/CGameDelegate.o \
    ../noudar-core/noudar-core/src/commands/IGameCommand.o \
    ../noudar-core/noudar-core/src/commands/CMoveActorCommand.o \
    ../noudar-core/noudar-core/src/commands/CLoadNewLevelCommand.o \
    ../noudar-core/noudar-core/src/commands/CTurnActorCommand.o \
    ../noudar-core/noudar-core/src/commands/CQuitCommand.o \
    ../noudar-core/noudar-core/src/commands/CNullCommand.o \
    ../noudar-core/noudar-core/src/commands/CEndTurnCommand.o \
    ../noudar-core/noudar-core/src/commands/CPickItemCommand.o \
    ../noudar-core/noudar-core/src/commands/CDropItemCommand.o \
    ../noudar-core/noudar-core/src/commands/CSuggestItemCommand.o \
    ../noudar-core/noudar-core/src/commands/CUseCurrentItemCommand.o \
    ../noudar-core/noudar-core/src/commands/CCycleNextItemCommand.o \
    ../noudar-core/noudar-core/src/commands/CCyclePreviousItemCommand.o \
    main.o \
    events.o \
    Win32Version/CGDIRenderer.o

TARGET = win32noudar.exe

$(TARGET):	$(OBJS)
	$(CXX) -o $(TARGET) $(OBJS) $(LIBS) $(LDFLAGS)
	i686-w64-mingw32-strip $(TARGET)

all:   $(TARGET)

packager:
	rm -f ./packer
	g++ -std=c++14 -opacker packer.cpp
	
data:	packager
	rm -f ./data.pfs
	ls res/*.*  | xargs ./packer

clean:
	rm -f $(OBJS) $(TARGET)
